<?php

function ys_pages_add_custom_fields() {
		if( function_exists('acf_add_local_field_group') ):

			// Content Modules
			acf_add_local_field_group(array (
				'key' => 'group_57c4eb64584da',
				'title' => 'Content',
				'fields' => array (
					array (
						'key' => 'field_57c4eb699286e',
						'label' => 'Modules',
						'name' => 'modules',
						'type' => 'flexible_content',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'button_label' => 'Add Row',
						'min' => '',
						'max' => '',
						'layouts' => array (
							array (
								'key' => '18a4eb881d57a',
								'name' => 'masthead',
								'label' => 'Masthead',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_57a6dbd91286f',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array (
										'key' => 'field_62a4fbb192870',
										'label' => 'Image',
										'name' => 'image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'thumbnail',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array (
										'key' => 'field_80594ad719c92',
										'label' => 'Show Call to Action',
										'name' => 'showCta',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 0,
									),
									array (
										'key' => 'field_85f617a6631ec',
										'label' => 'Call(s) To Action',
										'name' => 'cta',
										'type' => 'repeater',
										'instructions' => 'Add calls to action for the Masthead here',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_80594ad719c92',
													'operator' => '==',
													'value' => '1',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => '1',
										'max' => '3',
										'layout' => 'row',
										'button_label' => 'Add Row',
										'sub_fields' => array (
											array (
												'key' => 'field_85d629d5539ed',
												'label' => 'Text',
												'name' => 'text',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array (
												'key' => 'field_180a210af6452',
												'label' => 'Link Type',
												'name' => 'link_type',
												'type' => 'select',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => array (
													'internal_link' => 'Internal Link',
													'external_link' => 'External Link',
													'section_link' => 'Jump To Section',
												),
												'default_value' => array (
													0 => 'Internal Link',
												),
												'allow_null' => 0,
												'multiple' => 0,
												'ui' => 0,
												'ajax' => 0,
												'return_format' => 'value',
												'placeholder' => '',
											),
											array (
												'key' => 'field_185f7343e6433',
												'label' => 'Internal Link',
												'name' => 'internal_link',
												'type' => 'select',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_180a210af6452',
															'operator' => '==',
															'value' => 'internal_link',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => all_pages(),
												'default_value' => array (
												),
												'allow_null' => 0,
												'multiple' => 0,
												'ui' => 0,
												'ajax' => 0,
												'return_format' => 'value',
												'placeholder' => '',
											),
											array (
												'key' => 'field_892b7260d6434',
												'label' => 'External Link',
												'name' => 'external_link',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_180a210af6452',
															'operator' => '==',
															'value' => 'external_link',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array (
												'key' => 'field_782e722fd6435',
												'label' => 'Jump To Section',
												'name' => 'section_id',
												'type' => 'select',
												'instructions' => 'Section must exist on this page </br> You can add new sections <a href="/wp-admin/admin.php?page=site-settings">here</a>',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_180a210af6452',
															'operator' => '==',
															'value' => 'section_link',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => get_sections(),
												'default_value' => array (
												),
												'allow_null' => 0,
												'multiple' => 0,
												'ui' => 0,
												'ajax' => 0,
												'return_format' => 'value',
												'placeholder' => '',
											),
										),
									),
								),
								'min' => '',
								'max' => '1',
							),
							array (
								'key' => '57c4ea881d57a',
								'name' => 'title',
								'label' => 'Title',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_57a6dea98286f',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'instructions' => 'To be used where title needs to be bigger than normal section title',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
								),
								'min' => '',
								'max' => '',
							),
							array (
								'key' => '57c4eb774d57a',
								'name' => 'image',
								'label' => 'Image',
								'display' => 'block',
								'sub_fields' => array_merge( array (
									array (
										'key' => 'field_57c4ebb192870',
										'label' => 'Image',
										'name' => 'image',
										'type' => 'image',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'thumbnail',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									)
								), ys_add_additional_fields('12')),
								'min' => '',
								'max' => '',
							),
							array (
								'key' => '57c4ebb892871',
								'name' => 'text',
								'label' => 'Text',
								'display' => 'block',

								'sub_fields' => array_merge( array (
									array (
										'key' => 'field_57c4ebcc92872',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'instructions' => '',
										'required' => '',
										'conditional_logic' => '',
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array (
										'key' => 'field_270a919ff6452',
										'label' => 'Width',
										'name' => 'width',
										'type' => 'select',
										'instructions' => 'Width of the text block when it displays on the page',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'full' => 'Full',
											'half' => 'Half',
										),
										'default_value' => array (
										),
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'ajax' => 0,
										'return_format' => 'value',
										'placeholder' => '',
									),
									array (
										'key' => 'field_57c4ebdf92873',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => '',
										'conditional_logic' => '',
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => '',
									),
									array (
										'key' => 'field_80564eb719c92',
										'label' => 'Show Call to Action',
										'name' => 'showCta',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 0,
									),
									array (
										'key' => 'field_74a617a6631ec',
										'label' => 'Call To Action',
										'name' => 'cta',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_80564eb719c92',
													'operator' => '==',
													'value' => '1',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => '1',
										'max' => '1',
										'layout' => 'row',
										'button_label' => 'Add Row',
										'sub_fields' => array (
											array (
												'key' => 'field_74a619d5539ed',
												'label' => 'Text',
												'name' => 'text',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array (
												'key' => 'field_180e919af6452',
												'label' => 'Link Type',
												'name' => 'link_type',
												'type' => 'select',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => array (
													'internal_link' => 'Internal Link',
													'external_link' => 'External Link',
													'section_link' => 'Jump To Section',
												),
												'default_value' => array (
													0 => 'Internal Link',
												),
												'allow_null' => 0,
												'multiple' => 0,
												'ui' => 0,
												'ajax' => 0,
												'return_format' => 'value',
												'placeholder' => '',
											),
											array (
												'key' => 'field_581e7343e6433',
												'label' => 'Internal Link',
												'name' => 'internal_link',
												'type' => 'select',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_180e919af6452',
															'operator' => '==',
															'value' => 'internal_link',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => all_pages(),
												'default_value' => array (
												),
												'allow_null' => 0,
												'multiple' => 0,
												'ui' => 0,
												'ajax' => 0,
												'return_format' => 'value',
												'placeholder' => '',
											),
											array (
												'key' => 'field_298a7260d6434',
												'label' => 'External Link',
												'name' => 'external_link',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_180e919af6452',
															'operator' => '==',
															'value' => 'external_link',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array (
												'key' => 'field_691e722fd6435',
												'label' => 'Jump To Section',
												'name' => 'section_id',
												'type' => 'select',
												'instructions' => 'Section must exist on this page </br> You can add new sections <a href="/wp-admin/admin.php?page=site-settings">here</a>',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_180e919af6452',
															'operator' => '==',
															'value' => 'section_link',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => get_sections(),
												'default_value' => array (
												),
												'allow_null' => 0,
												'multiple' => 0,
												'ui' => 0,
												'ajax' => 0,
												'return_format' => 'value',
												'placeholder' => '',
											),
										),
									),
								), ys_add_additional_fields('329')),
								'min' => '',
								'max' => '',
							),
							array (
								'key' => '57c4ed839287f',
								'name' => 'video',
								'label' => 'Video',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_57c4ed8792880',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array (
										'key' => 'field_57c4ed9392881',
										'label' => 'Video URL',
										'name' => 'videoUrl',
										'type' => 'url',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
									),
								),
								'min' => '',
								'max' => '',
							),
							array (
								'key' => '57c4ec3b92874',
								'name' => 'textImage',
								'label' => 'Text & Image',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_57c4ec4792875',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array (
										'key' => 'field_57c4ec4f92876',
										'label' => 'Image',
										'name' => 'image',
										'type' => 'image',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'thumbnail',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array (
										'key' => 'field_57c4ec5792877',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => '',
										'conditional_logic' => '',
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => '',
									),
									array (
										'key' => 'field_58056eb719c92',
										'label' => 'Show Call to Action',
										'name' => 'showCta',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 0,
									),
									array (
										'key' => 'field_77a617a6631ec',
										'label' => 'Call To Action',
										'name' => 'cta',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_58056eb719c92',
													'operator' => '==',
													'value' => '1',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => '1',
										'max' => '1',
										'layout' => 'row',
										'button_label' => 'Add Row',
										'sub_fields' => array (
											array (
												'key' => 'field_77a619d5539ed',
												'label' => 'Text',
												'name' => 'text',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array (
												'key' => 'field_180a119af8456',
												'label' => 'Link Type',
												'name' => 'link_type',
												'type' => 'select',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => array (
													'internal_link' => 'Internal Link',
													'external_link' => 'External Link',
													'section_link' => 'Jump To Section',
												),
												'default_value' => array (
													0 => 'Internal Link',
												),
												'allow_null' => 0,
												'multiple' => 0,
												'ui' => 0,
												'ajax' => 0,
												'return_format' => 'value',
												'placeholder' => '',
											),
											array (
												'key' => 'field_581a7243z644',
												'label' => 'Internal Link',
												'name' => 'internal_link',
												'type' => 'select',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_180a119af8456',
															'operator' => '==',
															'value' => 'internal_link',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => all_pages(),
												'default_value' => array (
												),
												'allow_null' => 0,
												'multiple' => 0,
												'ui' => 0,
												'ajax' => 0,
												'return_format' => 'value',
												'placeholder' => '',
											),
											array (
												'key' => 'field_314a7261d6434',
												'label' => 'External Link',
												'name' => 'external_link',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_180a119af8456',
															'operator' => '==',
															'value' => 'external_link',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array (
												'key' => 'field_691e188fd6435',
												'label' => 'Jump To Section',
												'name' => 'section_id',
												'type' => 'select',
												'instructions' => 'Section must exist on this page </br> You can add new sections <a href="/wp-admin/admin.php?page=site-settings">here</a>',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_180a119af8456',
															'operator' => '==',
															'value' => 'section_link',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => get_sections(),
												'default_value' => array (
												),
												'allow_null' => 0,
												'multiple' => 0,
												'ui' => 0,
												'ajax' => 0,
												'return_format' => 'value',
												'placeholder' => '',
											),
										),
									),
									array (
										'key' => 'field_57c4ed549287e',
										'label' => 'Alignment',
										'name' => 'alignment',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'Left' => 'Left',
											'Right' => 'Right',
										),
										'default_value' => array (
											0 => 'Left',
										),
										'allow_null' => 1,
										'multiple' => 0,
										'ui' => 0,
										'ajax' => 0,
										'return_format' => 'value',
										'placeholder' => '',
									),
								),
								'min' => '',
								'max' => '',
							),
							array (
								'key' => '57c4ec6992878',
								'name' => 'textVideo',
								'label' => 'Text & Video',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_57c4ec7392879',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array (
										'key' => 'field_57c4ec7a9287a',
										'label' => 'Video URL',
										'name' => 'videoUrl',
										'type' => 'url',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
									),
									array (
										'key' => 'field_57c4ec9b9287b',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => '',
										'conditional_logic' => '',
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => '',
									),
									array (
										'key' => 'field_57c4ecd59287c',
										'label' => 'Alignment',
										'name' => 'alignment',
										'type' => 'select',
										'instructions' => '',
										'required' => '',
										'conditional_logic' => '',
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'Left' => 'Left',
											'Right' => 'Right',
										),
										'default_value' => array (
											0 => 'Left',
										),
										'allow_null' => '',
										'multiple' => '',
										'ui' => '',
										'ajax' => '',
										'return_format' => '',
										'placeholder' => '',
									),
								),
								'min' => '',
								'max' => '',
							),
							array (
								'key' => '38c4ac6112878',
								'name' => 'blockQuote',
								'label' => 'Block Quote',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_57fa9aa4f9266',
										'label' => 'Quote',
										'name' => 'content',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => '',
										'new_lines' => 'wpautop',
									),
								),
								'min' => '',
								'max' => '',
							),
							array (
								'key' => '57c4ee1d92882',
								'name' => 'list',
								'label' => 'List',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_57c4ee2492883',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '66',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array (
										'key' => 'field_57c4efeebe999',
										'label' => 'Columns',
										'name' => 'columns',
										'type' => 'select',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '33',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											1 => '1',
											2 => '2',
										),
										'default_value' => array (
											0 => 1,
										),
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 1,
										'ajax' => 1,
										'return_format' => 'value',
										'placeholder' => '',
									),
									array (
										'key' => 'field_68af9bb4f9266',
										'label' => 'Description',
										'name' => 'description',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => '',
										'new_lines' => 'wpautop',
									),
									array (
										'key' => 'field_57c4ee9fbe996',
										'label' => 'List Content',
										'name' => 'listContent',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => '',
										'max' => '',
										'layout' => 'table',
										'button_label' => 'Add Row',
										'sub_fields' => array (
											array (
												'key' => 'field_57c4eec5be997',
												'label' => 'List Items',
												'name' => 'listItem',
												'type' => 'text',
												'instructions' => '',
												'required' => '',
												'conditional_logic' => '',
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
										),
									),
								),
								'min' => '',
								'max' => '',
							),
							array (
								'key' => '57c4f03fbe99b',
								'name' => 'gallery',
								'label' => 'Gallery',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_57c4f047be99c',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array (
										'key' => 'field_57c4f07bbe99d',
										'label' => 'Gallery',
										'name' => 'gallery',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => '',
										'max' => '',
										'layout' => 'table',
										'button_label' => 'Add Row',
										'sub_fields' => array (
											array (
												'key' => 'field_57c4f091be99e',
												'label' => 'Image',
												'name' => 'image',
												'type' => 'image',
												'instructions' => '',
												'required' => 1,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'return_format' => 'array',
												'preview_size' => 'thumbnail',
												'library' => 'all',
												'min_width' => '',
												'min_height' => '',
												'min_size' => '',
												'max_width' => '',
												'max_height' => '',
												'max_size' => '',
												'mime_types' => '',
											),
										),
									),

								),
								'min' => '',
								'max' => '',
							),
							array (
								'key' => '57c6175b539e9',
								'name' => 'ctaBanner',
								'label' => 'Call To Action Banner',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_57c61787539ea',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array (
										'key' => 'field_57c61799539eb',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => '',
										'new_lines' => 'wpautop',
									),
									array (
										'key' => 'field_57c617a5539ec',
										'label' => 'Call To Action',
										'name' => 'cta',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => '1',
										'max' => '1',
										'layout' => 'row',
										'button_label' => 'Add Row',
										'sub_fields' => array (
											array (
												'key' => 'field_57c617b5539ed',
												'label' => 'Text',
												'name' => 'text',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array (
												'key' => 'field_580e719ed6432',
												'label' => 'Link Type',
												'name' => 'link_type',
												'type' => 'select',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => array (
													'internal_link' => 'Internal Link',
													'external_link' => 'External Link',
													'section_link' => 'Jump To Section',
												),
												'default_value' => array (
													0 => 'Internal Link',
												),
												'allow_null' => 0,
												'multiple' => 0,
												'ui' => 0,
												'ajax' => 0,
												'return_format' => 'value',
												'placeholder' => '',
											),
											array (
												'key' => 'field_580e7242d6433',
												'label' => 'Internal Link',
												'name' => 'internal_link',
												'type' => 'select',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_580e719ed6432',
															'operator' => '==',
															'value' => 'internal_link',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => all_pages(),
												'default_value' => array (
												),
												'allow_null' => 0,
												'multiple' => 0,
												'ui' => 0,
												'ajax' => 0,
												'return_format' => 'value',
												'placeholder' => '',
											),
											array (
												'key' => 'field_580e7260d6434',
												'label' => 'External Link',
												'name' => 'external_link',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_580e719ed6432',
															'operator' => '==',
															'value' => 'external_link',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array (
												'key' => 'field_580e726fd6435',
												'label' => 'Jump To Section',
												'name' => 'section_id',
												'type' => 'select',
												'instructions' => 'Section must exist on this page </br> You can add new sections <a href="/wp-admin/admin.php?page=site-settings">here</a>',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_580e719ed6432',
															'operator' => '==',
															'value' => 'section_link',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => get_sections(),
												'default_value' => array (
												),
												'allow_null' => 0,
												'multiple' => 0,
												'ui' => 0,
												'ajax' => 0,
												'return_format' => 'value',
												'placeholder' => '',
											),
										),
									),
								),
								'min' => '',
								'max' => '',
							),
							array (
								'key' => '57c61d152d54b',
								'name' => 'officeMap',
								'label' => 'Office Map',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_57c61d232d54c',
										'label' => 'Show Office Map',
										'name' => 'showOfficeMap',
										'type' => 'true_false',
										'instructions' => 'Enable to show interactive office map module',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 1,
									),
								),
								'min' => '',
								'max' => '',
							),
							array (
								'key' => '68a62d552d54b',
								'name' => 'newsletterSignup',
								'label' => 'Newsletter Sign Up',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_57c61d232d54c',
										'label' => 'Show newsletter sign up module',
										'name' => 'showNewsletterSignup',
										'type' => 'true_false',
										'instructions' => 'Enable to show newsletter sign up module',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 1,
									),
								),
								'min' => '',
								'max' => '',
							),
							array (
								'key' => '69b63d552d54b',
								'name' => 'practiceLeaders',
								'label' => 'Practice Leaders',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_581185a91de7a',
										'label' => 'Practice Leaders',
										'name' => 'practiceLeaders',
										'type' => 'relationship',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'post_type' => array (
											0 => 'people',
										),
										'taxonomy' => array (
										),
										'filters' => '',
										'elements' => '',
										'min' => '',
										'max' => 6,
										'return_format' => 'object',
									),
								),
								'min' => '',
								'max' => '1',
							),
							array (
								'key' => '69a73d752d54b',
								'name' => 'dataList',
								'label' => 'Data List',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_58125bde839a9',
										'label' => 'Data List',
										'name' => 'dataList',
										'type' => 'repeater',
										'instructions' => 'Use where list items have a title and content',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => '',
										'max' => '',
										'layout' => 'table',
										'button_label' => 'Add Row',
										'sub_fields' => array (
											array (
												'key' => 'field_58125c12839aa',
												'label' => 'Title',
												'name' => 'title',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array (
												'key' => 'field_58125c17839ab',
												'label' => 'Content',
												'name' => 'content',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
										),
									),
								),
								'min' => '',
								'max' => '',
							),
						),
					),
				),
				'location' => array (
					array (
						array (
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'page',
						),
					),
					array (
						array (
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'articles',
						),
						array (
							'param' => 'page_template',
							'operator' => '!=',
							'value' => 'home.php',
						),
					),
					array (
						array (
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'services',
						),
					),
					array (
						array (
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'industries',
						),
					),
				),
				'menu_order' => 9,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => 1,
				'description' => '',
			));

			// Home page fields
			acf_add_local_field_group(array (
				'key' => 'group_57f31af4d2dd2',
				'title' => 'Featured Services and Industries',
				'fields' => array (
					array (
						'key' => 'field_57f31b3070aba',
						'label' => 'Featured Services and Industries',
						'name' => 'featured_services_and_industries',
						'type' => 'relationship',
						'instructions' => 'Select which services and industries to feature on the home page.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array (
							0 => 'services',
							1 => 'industries',
						),
						'taxonomy' => array (
						),
						'filters' => '',
						'elements' => '',
						'min' => '8',
						'max' => '8',
						'return_format' => 'object',
					),
				),
				'location' => array (
					array (
						array (
							'param' => 'page_template',
							'operator' => '==',
							'value' => 'home.php',
						),
					),
				),
				'menu_order' => 2,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => 1,
				'description' => '',
			));

		endif;
}
add_action('init', 'ys_pages_add_custom_fields');

?>
